add html and css to people.html
poe-iit/poe-website pull request #8
Opened 2021-03-12 04:29 UTC by saugusth

2021-03-15 20:59 UTC, ilopez5 requested changes
Looks good so far, I have a few suggestions/requests:
1. Maybe add a border radius to the images, so that they are circles
2. The lines within a team section doesn't look that good
3. Add a section for Past Contributors (get a list from Dr. Dan)
4. If you aren't set on the placeholder image, maybe a generic silhouette would look good? I leave the final decision up to the website team.

2021-03-16 00:27 UTC, sahilatIIT requested changes
Overall it looks really good. Nice job on using the Bootstrap grid here. I left some comments, but overall I think that maybe the images should be smaller. I also think that we can leave the subgroups and titles out (like website, VR, etc.), and possibly even leave the groups out (software, hardware), and just list people involved with the IPRO per semester. We could possibly add a section in the beginning focusing on Dr. Dan with a short bio.

2021-03-16 00:27 UTC, sahil-at-home1 commented on assets/css/styles.css
> +.style-fix img {
I think we should try to use bootstrap as much as possible to simplify our code, while keeping it fluid and responsive. Bootstrap includes HTML classes to setup images, along with borders, and different shapes (like circles). I noticed that the images are different sizes, which might make it difficult for bootstrap to align them alone. In that case or some other bootstrap limitation, I support this.

2021-03-16 00:27 UTC, sahil-at-home1 commented on people.html
> +                    <img src="assets/images/Julia.jpeg" alt="Place holder">
small typo, should be `.jpg`

2021-03-16 00:27 UTC, sahilatIIT commented on people.html
> +            <div style="background-color:black; border: 1px solid;"></div>
I think its better to minimize usage of inline CSS, but this is small so I am open to keeping it. If we wanted to use bootstrap we could use something like `<hr></hr>` or `<div class="divider"></div>`

2021-03-17 23:34 UTC, merged